export const STUDENT_SUCCESS = 'STUDENT_SUCCESS';
export const STUDENT_FAILURE = 'STUDENT_FAILURE';

export const SAVE_STUDENT_REQUEST = 'SAVE_STUDENT_REQUEST';
export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';